version: '3.7'

services:
  fluentd:
    build: ./build
    container_name: fluentd
    network_mode : host
    volumes:
      - ./conf:/fluentd/etc
    ports:
      - "2055:2055"
      - "2055:2055/udp"
    logging:
       driver: "json-file"
       options:
          max-file: "5"
          max-size: "10m"
